snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%env(resolve:REDIS_URL)%'
            
services:
    Predis\Client: '@snc_redis.default'
    Predis\ClientInterface: '@Predis\Client'